### ISSUE TITLE
savestate

### ISSUE THREAD

**Issue by tanapthetimid** [poohcom1/bug-game#1]
im working on savestate

**Comment by tanapthetimid** [comment]
General design idea:
-each object will have a save() and load() function that will serialize/load data into/from plain text.
-central loader/saver module will need to keep track of which objects should be saved and loaded in a reference list

**Comment by poohcom1** [comment]
sounds good. Currently the structure is that there are parent scripts for objects (Enemy.gd, Structure.gd), which I think has most of the necessary stuff you'd want to serialize (health, battery, position), so you could just make the save load function in those scripts
