### ISSUE TITLE
Game don't start

### ISSUE THREAD

**Issue by bl00dy1837** [poohcom1/bug-game#2]
`Godot Engine v3.4.stable.arch_linux - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Found renderers:
Renderer 0: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2) with priority: 20
Renderer 1: AMD TURKS (DRM 2.50.0 / 5.15.2-arch1-1, LLVM 13.0.0) with priority: 30
Using renderer: AMD TURKS (DRM 2.50.0 / 5.15.2-arch1-1, LLVM 13.0.0)
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
XcursorGetTheme could not get cursor theme
VisualServerWrapMT: Creating render thread
VisualServerWrapMT: Starting render thread
Using GLES3 video driver
OpenGL ES 3.0 Renderer: AMD TURKS (DRM 2.50.0 / 5.15.2-arch1-1, LLVM 13.0.0)
OpenGL ES Batching: ON
	OPTIONS
	max_join_item_commands 16
	colored_vertex_format_threshold 0.25
	batch_buffer_size 16384
	light_scissor_area_threshold 1
	item_reordering_lookahead 4
	light_max_join_items 32
	single_rect_fallback False
	debug_flash False
	diagnose_frame False
VisualServerWrapMT: Finished render thread
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.pci-0000_00_1b.0.analog-stereo
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
JoypadLinux: udev enabled and loaded successfully.
 
Loading resource: res://default_bus_layout.tres
CORE API HASH: 15843999809385478705
EDITOR API HASH: 5561212406590411750
Loading resource: res://default_env.tres
Loading resource: res://system/GameManager.gd
Loading resource: res://entities/player/Player.gd
Loading resource: res://pickups/Entity.gd
Loading resource: res://system/AnimUtil.gd
Loading resource: res://weapons/Weapon.gd
Loading resource: res://assets/SE/Warning1.mp3
ERROR: Cannot open file 'res://.import/Warning1.mp3-0fbe6e53ea10b79976407f236371ccc9.mp3str'.
   at: load_interactive (core/io/resource_format_binary.cpp:939)
ERROR: Failed loading resource: res://.import/Warning1.mp3-0fbe6e53ea10b79976407f236371ccc9.mp3str. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading resource: res://assets/SE/Warning1.mp3. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
SCRIPT ERROR: Parse Error: Can't preload resource at path: res://assets/SE/Warning1.mp3
          at: GDScript::reload (res://weapons/Weapon.gd:9)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:566)
Loading resource: res://weapons/modules/Modules.gd
SCRIPT ERROR: Parse Error: The class "Weapon" couldn't be fully loaded (script error or cyclic dependency).
          at: GDScript::reload (res://entities/player/Player.gd:60)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:566)
Loading resource: res://ui/MainHUD.gd
Loading resource: res://ui/dialogue/DialogueContainer.gd
SCRIPT ERROR: Parse Error: The class "Player" couldn't be fully loaded (script error or cyclic dependency).
          at: GDScript::reload (res://system/GameManager.gd:16)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:566)
ERROR: Script does not inherit a Node: res://system/GameManager.gd
   at: start (main/main.cpp:1819)
Loading resource: res://ui/LoadingScreen.tscn
Loading resource: res://assets/ui/scanlines.png
ERROR: Condition "!f" is true. Returned: ERR_CANT_OPEN
   at: _load_data (scene/resources/texture.cpp:466)
ERROR: Failed loading resource: res://.import/scanlines.png-3fb3ec1102bb101369c54b6a7c0ca504.stex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading resource: res://assets/ui/scanlines.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://ui/LoadingScreen.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/ui/scanlines.png
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://ui/LoadingScreen.tscn'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://ui/LoadingScreen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Can't autoload: res://ui/LoadingScreen.tscn
   at: start (main/main.cpp:1810)
Loading resource: res://stages/menu/MainMenu.tscn
Loading resource: res://ui/menu/MenuButton.tscn
Loading resource: res://ui/menu/MenuButton.gd
Loading resource: res://system/OneShotAudio.gd
Loading resource: res://assets/SE/MenuTick.ogg
ERROR: Cannot open file 'res://.import/MenuTick.ogg-80702ebe6eb95687380381cd0f3fc538.oggstr'.
   at: load_interactive (core/io/resource_format_binary.cpp:939)
ERROR: Failed loading resource: res://.import/MenuTick.ogg-80702ebe6eb95687380381cd0f3fc538.oggstr. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading resource: res://assets/SE/MenuTick.ogg. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://ui/menu/MenuButton.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/SE/MenuTick.ogg
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://ui/menu/MenuButton.tscn'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://ui/menu/MenuButton.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: res://stages/menu/MainMenu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://ui/menu/MenuButton.tscn
   at: poll (scene/resources/resource_format_text.cpp:412)
ERROR: Failed to load resource 'res://stages/menu/MainMenu.tscn'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: res://stages/menu/MainMenu.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
ERROR: Failed loading scene: res://stages/menu/MainMenu.tscn
   at: start (main/main.cpp:1998)
PulseAudio: context terminated
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2064)
Leaked instance: ViewportTexture:1248 - Resource path: 
Leaked instance: SceneTree:1244
Leaked instance: Viewport:1245 - Node name: root
Leaked instance: ProceduralSky:1253 - Resource path: res://default_env.tres::1
Leaked instance: Environment:1254 - Resource path: res://default_env.tres
Leaked instance: World:1249 - Resource path: 
Leaked instance: Physics2DDirectSpaceStateSW:1247
Leaked instance: World2D:1246 - Resource path: 
Leaked instance: MultiplayerAPI:1251
Leaked instance: Image:1271 - Resource path: 
Leaked instance: BulletPhysicsDirectSpaceState:1250
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417)
Resource still in use: res://default_env.tres (Environment)
Resource still in use: res://default_env.tres::1 (ProceduralSky)
Orphan StringName: tree_changed
Orphan StringName: _vp_unhandled_input1245
Orphan StringName: _server_disconnected
Orphan StringName: network_peer_connected
Orphan StringName: World2D
Orphan StringName: BulletPhysicsDirectSpaceState
Orphan StringName: _network_peer_connected
Orphan StringName: ProceduralSky
Orphan StringName: _network_peer_disconnected
Orphan StringName: node_added
Orphan StringName: World
Orphan StringName: Viewport
Orphan StringName: network_peer_disconnected
Orphan StringName: node_removed
Orphan StringName: Physics2DDirectSpaceStateSW
Orphan StringName: root
Orphan StringName: MultiplayerAPI
Orphan StringName: Environment
Orphan StringName: _vp_gui_input1245
Orphan StringName: _vp_input1245
Orphan StringName: _connection_failed
Orphan StringName: SceneTree
Orphan StringName: connected_to_server
Orphan StringName: node_renamed
Orphan StringName: connection_failed
Orphan StringName: Image
Orphan StringName: _vp_unhandled_key_input1245
Orphan StringName: _connected_to_server
Orphan StringName: ViewportTexture
Orphan StringName: server_disconnected
StringName: 30 unclaimed string names at exit.
ERROR: There are still MemoryPool allocs in use at exit!
   at: cleanup (core/pool_vector.cpp:63)
`

**Comment by poohcom1** [comment]
Hm... seems like there are a lot of resource import errors mixed in with cyclic code imports (the latter shouldn't be an issue), so I'm assuming most of the issue came from resource imports.

Just to check, are you running the game from the Godot editor project list? Godot does require you open the project at least once before you can run the game in the editor to import all the assets.

**Comment by bl00dy1837** [comment]
oh thx, opening in the editor fixed it. sorry for bothering
